### ISSUE TITLE
Not working train.py

### ISSUE THREAD

**Issue by ensarkarabudak** [Armour/Automatic-Image-Colorization#4]
I get an error when I run **python train.py**

```
Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from config import *
  File "/home/hellofriend/İndirilenler/Automatic-Image-Colorization-master/config.py", line 35
SyntaxError: Non-ASCII character '\xc4' in file /home/hellofriend/İndirilenler/Automatic-Image-Colorization-master/config.py on line 35, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

**Comment by youyingyin** [comment]
I think you have add some comment in config.py which cant be coded in python2.7. you should add    # -*- coding: utf-8 -*-     at the beginning of  config.py

**Comment by Armour** [comment]
Hi, @ensarkarabudak @youyingyin  please take a look at the new [release](https://github.com/Armour/Automatic-Image-Colorization/releases/tag/2.0).
