### ISSUE TITLE
Failed to restore model - test.py

### ISSUE THREAD

**Issue by matrob67** [Armour/Automatic-Image-Colorization#6]
I have the following error when running test.py with the pretrained model:

> Init file path
Throwing all gray space images now... this may takes some time..
Init placeholder
Init vgg16 model
C:\Users\mathi\Desktop\Automatic-Image-Colorization-python3\vgg\vgg16.npy
npy file loaded
Init residual encoder model
build model started
build model finished: 3s
Init summaries
Init model saver
Init graph
Merge all summaries
Start input enqueue threads
Failed to restore model

Any idea on what went wrong ?

**Comment by Armour** [comment]
Hi @matrob67, please take a look at the new [release](https://github.com/Armour/Automatic-Image-Colorization/releases/tag/2.0).
