### ISSUE TITLE
Error at training time

### ISSUE THREAD

**Issue by kamurthianudeep** [Armour/Automatic-Image-Colorization#7]
hello,
I have followed your steps as specified, but while training the images faced a problem in train program  in line `plt.imsave("%s/images/%s.JPEG" % (train_summary, str(step)), summary_image)`  I have changed iterations, batch size and buffer size a in the config file. The iteration stops at number specified in save_step. In line 52 of train.py , step = sess.run(global_step) was altered to step = sess.run(global_step-1) to avoid the error. But on this it goes to infinity loop. Could you please help.

Regards,
Anudeep

**Comment by Armour** [comment]
Hi @kamurthianudeep, please take a look at the new [release](https://github.com/Armour/Automatic-Image-Colorization/releases/tag/2.0).
